# 과제 1
## Q1. 


<div class="alert alert-success">
[문제1]     
    
원소가 1부터 5까지인 배열 arr이 있다. 각각의 요소의 루트를 씌운 값의 총합을 구하시오. 
</div>

------------
[힌트]  
np.arange(1, 6)  
list = [1,2,3,4,5]   
8.382332347441762  

In [2]:
import numpy as np

arr = np.arange(1, 6)
result = np.sum(np.sqrt(arr))
print(result) 

8.382332347441762


## Q2. 

<div class="alert alert-success">
[문제2]
    
    
다음과 같은 배열 arr2를 만드시오.  
    
    
arr2 = ( arr의 총합, arr의 평균, arr의 최소값, arr의 최대값)  
[15.  3.  1.  5.]  
</div>

In [3]:
arr2 = np.array((np.sum(arr), np.mean(arr), np.min(arr), np.max(arr)))
print(arr2)

[15.  3.  1.  5.]


## Q3.

<div class="alert alert-success">
[문제3]
    
    
arr2의 구조를 확인하고(shape),
arr2를 전치(transpose)한 배열 arr3를 만드시오.
</div>

------------
[힌트]  

arr3의 출력 결과

[[15.]  
 [ 3.]   
 [ 1.]  
 [ 5.]]

In [4]:
print(arr2.shape) # (4,)
arr2 = np.reshape(arr2, [1, 4])
print(arr2)
print(arr2.shape) # (1, 4)
arr3 = np.transpose(arr2)
print(arr3)
print(arr3.shape)  # (4, 1)

(4,)
[[15.  3.  1.  5.]]
(1, 4)
[[15.]
 [ 3.]
 [ 1.]
 [ 5.]]
(4, 1)



## Q4. 


<div class="alert alert-success">
[문제4]
    
    
arr2와 arr3를 행렬 곱 연산한 결과 값은 ? 
</div>

[힌트]


 260.
 
 
 또는
 
 
 
 [[225.  45.  15.  75.]  
 [ 45.   9.   3.  15.]   
 [ 15.   3.   1.   5.]   
 [ 75.  15.   5.  25.]]   




In [4]:
# (1x4)*(4x1) = (1x1) 스칼라 
result = np.matmul(arr2, arr3)
print(result)

[[260.]]


In [5]:
# (4x1)*(1x4) = (4x4) 
result = np.matmul(arr3, arr2)
print(result)

[[225.  45.  15.  75.]
 [ 45.   9.   3.  15.]
 [ 15.   3.   1.   5.]
 [ 75.  15.   5.  25.]]


# 과제 2
## Q5.


<div class="alert alert-success">
[문제5]
    
    
arange 함수를 이용하여 원소가 1부터 16까지인 배열 arr을 만드세요.
</div>


In [6]:
arr = np.arange(1, 17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Q6. 


<div class="alert alert-success">
[문제6]
    
    
arr 배열을 4행 4열로 형상 변경하세요.
</div>


In [7]:
arr = np.reshape(arr, [4, 4])
print(arr) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## Q7. 


<div class="alert alert-success">
[문제7]
    
arr에 대해 인덱싱과 슬라이싱을 이용하여 다음과 같은 배열 arr2, arr3를 만드시오.  
arr2 :   
 [[2 3 4]  
 [6 7 8]]

arr3 :   
 [[5 6 7]]  
</div>




In [8]:
# 0::2 ==> 0부터 2씩 증가하여 끝까지
arr2 = arr[0:2, 1:4]
print("arr2\n", arr2)

arr3 = arr[1:2, 0:3]
print("arr3\n", arr3)

arr2
 [[2 3 4]
 [6 7 8]]
arr3
 [[5 6 7]]


## Q8.

<div class="alert alert-success">
[문제8]
    
arr3를 전치(transpose)하세요.
</div>

-----------------
[힌트]


[[5]  
 [6]  
 [7]]  


In [9]:
arr3t = np.transpose(arr3)
print(arr3t)

[[5]
 [6]
 [7]]


## Q9.


<div class="alert alert-success">
[문제9]
    
arr2와 arr3를 행렬 연산한 결과를 구하시오.
</div>

-----------------




**[결과]**  
[[ 56]  
 [128]]

In [10]:
result = np.matmul(arr2, arr3t)
print( result )

[[ 56]
 [128]]


# 과제 3
## Q10.

<div class="alert alert-success">
[문제10]
    
np.random을 이용하여 모든 요소의 값이 3 <= 값 < 7인   
요소 4개를 갖는 1차원 배열 arr을 생성하시오.  
예시) arr = [4, 3, 4, 6]  
</div>





In [11]:
import numpy as np
arr = np.random.randint(3, 7, size=4)
arr

array([3, 4, 5, 6])

## Q11. 

<div class="alert alert-success">
[문제11]
    
arr을 2*2 형상 변경하시오.
</div>


In [12]:
arr = arr.reshape(2,2)
arr

array([[3, 4],
       [5, 6]])

## Q12. 


<div class="alert alert-success">
[문제12]
다음과 같이 동작하는 로또 번호 생성기를 작성하시오.
    
    
    - 사용자로부터 로또 번호를 몇 개 생성할지 입력받는다    
    
    - 사용자가 입력한 개수 만큼 로또 번호를 생성하여 출력한다    
    
    - 로또번호는 숫자가 작은 수부터 순서대로 정렬하여 출력한다
    
    - 로또 번호는 1부터 46까지 서로 다른 6개의 정수로 이루어져있다    
        
    - 로또 번호 생성기 로직은 함수로 작성하여 재활용이 가능하도록 한다    
   

</div>
    
[실행 예시]
로또번호를 몇 개 생성할까요? 3  
1. 로또번호: [10 13 16 30 37 41]  
2. 로또번호: [ 4 10 15 25 29 42]  
3. 로또번호: [ 6 26 31 39 40 45]  

  

In [13]:
def createLottoNumber(count):
    for i in range(count):
        lotto_num = np.random.randint(1, 46, size=6)
        lotto_num.sort() # 값 정렬
        print("{}. 로또번호: {}".format(i+1, lotto_num))
    
count = int(input("로또번호를 몇 개 생성할까요? "))
createLottoNumber(count)

로또번호를 몇 개 생성할까요? 3
1. 로또번호: [ 1  1  3 35 35 38]
2. 로또번호: [ 1  9 13 14 15 40]
3. 로또번호: [ 2 13 25 28 31 36]


## Q13. 


<div class="alert alert-success">
    
[문제13]
    
오늘의 로또번호는 [9, 12, 17, 21, 40, 42]입니다.  
    
오늘의 로또번호 합보다 더 큰 조합을 가지고 있는 경우, 이벤트 쿠폰을 발행하려고 합니다.
    
몇 장의 이벤트 쿠폰을 발행해야하는지 판단하는 로직을 작성하세요

</div>

[실행 예시]



로또번호를 몇 개 생성할까요? 3
1. 로또번호: [ 1 15 36 39 41 45]  
이벤트 당첨, 오늘의 로또번호 합= 141, 당첨된 로또번호 합=177
2. 로또번호: [ 6  9 12 19 27 42]  
3. 로또번호: [ 4  7 36 39 39 44]  
이벤트 당첨, 오늘의 로또번호 합= 141, 당첨된 로또번호 합=169


In [14]:
today = np.array([9, 12, 17, 21, 40, 42])

def createLottoNumber2(count):
    for i in range(count):
        lotto_num = np.random.randint(1, 46, size=6)
        lotto_num.sort() # 값 정렬
        print("{}. 로또번호: {}".format(i+1, lotto_num))
        
        coupon_cnt = 0
        if lotto_num.sum() > today.sum():
            print("이벤트 당첨, 오늘의 로또번호 합= {}, 당첨된 로또번호 합={}".format(today.sum(), lotto_num.sum()))
    
count = int(input("로또번호를 몇 개 생성할까요? "))
createLottoNumber2(count)

로또번호를 몇 개 생성할까요? 5
1. 로또번호: [ 4  4 10 23 40 43]
2. 로또번호: [ 5 11 31 35 38 45]
이벤트 당첨, 오늘의 로또번호 합= 141, 당첨된 로또번호 합=165
3. 로또번호: [ 1  8 15 24 41 42]
4. 로또번호: [ 2  7 12 15 17 26]
5. 로또번호: [15 16 23 28 36 45]
이벤트 당첨, 오늘의 로또번호 합= 141, 당첨된 로또번호 합=163


# 과제 4
## Q14. 


<div class="alert alert-success">
    
[문제14]
    
수학 시험 답안 채점 프로그램을 만드시오.
    
    정답 = [3, 2, 1, 4, 4, 3, 4, 4, 3, 3]
    
    - 문제 수: 10
    - 보기: 1번 ~ 5번
    - 학생들의 샘플 답안 생성: 10개
    - 문항 별 정오답 여부 출력
    - 10점 만점에 몇 점인지 출력
</div>


1. 채점결과: [False  True False False  True False False False  True  True], 점수: 4
2. 채점결과: [False  True False  True False False False  True False False], 점수: 3
3. 채점결과: [ True  True  True False False False False  True False  True], 점수: 5
4. 채점결과: [False False  True False False  True False False False  True], 점수: 3
5. 채점결과: [False  True False  True False  True False  True False False], 점수: 4
6. 채점결과: [False False False  True False False False False False False], 점수: 1
7. 채점결과: [False  True  True False  True False False False False  True], 점수: 4
8. 채점결과: [False  True  True False False False  True False False False], 점수: 3
9. 채점결과: [ True False False False False  True False  True False False], 점수: 3
10. 채점결과: [False  True  True False False False  True False False False], 점수: 3


In [15]:
# 주어진 코드
correct = np.array([3, 2, 1, 4, 4, 3, 4, 4, 3, 3])

count = 10
students = 10
answers = np.random.randint(1, 5, size=count*students)
answers = answers.reshape(count, students)

In [16]:
def check_answer_sheet(correct, answers):
    for i in range(len(answers)):
        print("{}. 채점결과: {}, 점수: {}".format(i+1, answers[i] == correct, (answers[i] == correct).sum()))

check_answer_sheet(correct, answers)

1. 채점결과: [False  True False False False  True False False  True False], 점수: 3
2. 채점결과: [False False False False False False False False  True False], 점수: 1
3. 채점결과: [False False False False False False False False  True False], 점수: 1
4. 채점결과: [False False False False False False  True False False False], 점수: 1
5. 채점결과: [False False False  True False False  True  True  True False], 점수: 4
6. 채점결과: [False False False False False False False False False False], 점수: 0
7. 채점결과: [False False  True False False  True  True  True False False], 점수: 4
8. 채점결과: [False  True False False False False False  True  True False], 점수: 3
9. 채점결과: [False  True  True False False False False  True False False], 점수: 3
10. 채점결과: [ True False False False False False False False  True False], 점수: 2
