In [60]:
values = """산토끼 토끼야. 어디를 가느냐. 깡충깡충 뛰면서. 어디를 가느냐.
산고개 고개를. 나혼자 넘어서. 토실토실 알밤을. 주워 올테야"""

def get_char_count(values, char):
    count = 0
    for i in values:
        if(i == char):
            count += 1
    return count
print(get_char_count(values, '토'))

4


In [61]:
import numpy as np

In [62]:
list1 = [1, 2, 3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [63]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [66]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.random.rand(2,3)

array([[0.47583117, 0.93555994, 0.37933241],
       [0.6300322 , 0.36371257, 0.66723259]])

In [69]:
np.random.randint(1, 10, size = 10)

array([2, 1, 5, 1, 9, 5, 4, 7, 8, 7])

In [70]:
arr2 = np.arange(16)
arr2.shape

(16,)

In [71]:
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
arr2.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [73]:
arr2.dtype

dtype('int32')

In [74]:
arr2.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [75]:
arr2[6]

6

In [76]:
arr2[6:10]

array([6, 7, 8, 9])

In [77]:
arr2[10] = 100

In [78]:
arr2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,  11,  12,
        13,  14,  15])

In [79]:
arr3 = np.arange(16).reshape(4,4)

In [80]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
arr3[2,1]

9

In [82]:
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [83]:
score_arr [score_arr< 80]

array([70, 65, 75])

In [109]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [110]:
arr1 = np.sqrt(arr)
print(arr1)
np.sum(arr1)

[1.         1.41421356 1.73205081 2.         2.23606798]


8.382332347441762

In [125]:
arr2 = [np.sum(arr),np.mean(arr),np.min(arr),np.max(arr)]
arr2 = np.array(arr2)
arr2

array([15.,  3.,  1.,  5.])

In [127]:
arr2.shape
arr3 = arr2.reshape([1,4]).T
arr3

array([[15.],
       [ 3.],
       [ 1.],
       [ 5.]])

In [131]:
arr2 * arr3
np.matmul(arr2,arr3)

array([260.])

In [137]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [143]:
arr2 = arr[0:2,1:4]
print(arr2)
arr3 = arr[1,0:3]
print(arr3)

[[2 3 4]
 [6 7 8]]
[5 6 7]


In [146]:
arr3 = arr[1,0:3].reshape(1,3).T
arr3

array([[5],
       [6],
       [7]])

In [174]:
arr = np.arange(1,17).reshape(4,4)
arr2 = arr[0:2,1:4]
arr3 = arr[1,0:3].reshape(1,3).T
np.matmul(arr2, arr3)

array([[ 56],
       [128]])

In [178]:
arr = np.random.randint(3,7,size = 4)
arr

array([3, 4, 5, 5])

In [179]:
arr.reshape(2,2)

array([[3, 4],
       [5, 5]])

In [193]:
i = int(input("로또번호를 몇 개 생성할까요?:"))
k = 0
for k in range(i):
    rodd = np.random.randint(1,47,size = 6)
    rodds = sorted(rodd)
    k = k + 1
    print(k,".로또번호:",rodds) 


로또번호를 몇 개 생성할까요?:3
1 .로또번호: [11, 22, 23, 33, 38, 41]
2 .로또번호: [15, 19, 25, 35, 40, 42]
3 .로또번호: [1, 10, 10, 14, 38, 39]


In [4]:
import numpy as np
today = np.array([9, 12, 17, 21, 40, 42])

def createLottoNumber2(count):
   # 작성하시오
    for k in range(count):
        rodd_cou = np.random.randint(1,47,size=6)
        rodd_cous = rodd_cou.sort()
        rodd_cous_sum=np.sum(rodd_cou)
        today_sum=np.sum(today)
        if rodd_cous_sum > today_sum:
            print("{}.로또번호:{}\n\t이벤트 당첨, 오늘의 로또번호 합={}, 당첨된 로또번호 합={}".format(k+1,rodd_cou,rodd_cous_sum,today_sum))
        else:
            print("{}.로또번호:{}".format(k+1,rodd_cou))
        k = k + 1
        
count = int(input("로또번호를 몇 개 생성할까요? "))
createLottoNumber2(count)

로또번호를 몇 개 생성할까요? 5
1.로또번호:[10 11 21 25 39 46]
	이벤트 당첨, 오늘의 로또번호 합=152, 당첨된 로또번호 합=141
2.로또번호:[ 7 13 13 29 34 37]
3.로또번호:[17 21 24 38 40 46]
	이벤트 당첨, 오늘의 로또번호 합=186, 당첨된 로또번호 합=141
4.로또번호:[ 7  8 11 12 14 14]
5.로또번호:[ 5  9 25 28 34 38]


In [20]:
correct = np.array([3, 2, 1, 4, 4, 3, 4, 4, 3, 3])

count = 10
students = 10
answers = np.random.randint(1, 5, size=count*students)
answers = answers.reshape(count, students)
print(answers)
print(answers[9])

[[3 4 1 4 2 1 2 4 3 1]
 [4 3 4 3 3 1 2 2 3 3]
 [4 3 1 1 2 4 1 4 3 2]
 [1 2 3 2 4 3 2 1 3 2]
 [2 4 1 2 2 3 1 1 4 4]
 [2 2 3 3 1 2 1 1 1 3]
 [2 3 3 2 4 4 1 3 1 3]
 [4 3 4 1 3 1 4 1 2 2]
 [4 1 4 3 2 1 2 2 4 4]
 [3 3 1 1 2 4 1 1 4 1]]
[3 3 1 1 2 4 1 1 4 1]


In [21]:
def check_answer_sheet(correct, answers):
    # 작성하시오
    for k in range(len(answers)):
        print("{}.채점결과:{},점수:{}".format(k+1,answers[k] == correct, (answers[k] == correct).sum()))

check_answer_sheet(correct, answers)

1.채점결과:[ True False  True  True False False False  True  True False],점수:5
2.채점결과:[False False False False False False False False  True  True],점수:2
3.채점결과:[False False  True False False False False  True  True False],점수:3
4.채점결과:[False  True False False  True  True False False  True False],점수:4
5.채점결과:[False False  True False False  True False False False False],점수:2
6.채점결과:[False  True False False False False False False False  True],점수:2
7.채점결과:[False False False False  True False False False False  True],점수:2
8.채점결과:[False False False False False False  True False False False],점수:1
9.채점결과:[False False False False False False False False False False],점수:0
10.채점결과:[ True False  True False False False False False False False],점수:2
