# 6.2 인공신경망 구성하기

## 6.2.2 인공신경망 구성하기 - 퀴즈

### 문제 1

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_boston

# 데이터 불러오기
boston = load_boston()
boston_df = pd.DataFrame(data=boston.data, columns=boston.feature_names)
boston_df['PRICE'] = boston.target
boston_df.head()

C:\Users\cso13\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [2]:
boston_df.shape

(506, 14)

In [3]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

y = boston_df['PRICE']
x = boston_df.drop(['PRICE'], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42)

model = Sequential()
model.add(Dense(20, input_dim = 13, activation = 'relu'))
model.add(Dense(1, activation = 'relu'))

model.compile(loss = 'mean_squared_error',
             optimizer = 'adam',
             metrics = ['mse'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                280       
                                                                 
 dense_1 (Dense)             (None, 1)                 21        
                                                                 
Total params: 301
Trainable params: 301
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.fit(x_train, y_train, epochs = 50, batch_size = 4)

Epoch 1/50
95/95 [==============================] - 1s 1ms/step - loss: 613.4543 - mse: 613.4543
Epoch 2/50
95/95 [==============================] - 0s 1ms/step - loss: 613.4543 - mse: 613.4543
Epoch 3/50
95/95 [==============================] - 0s 1ms/step - loss: 613.4543 - mse: 613.4543
Epoch 4/50
95/95 [==============================] - 0s 1ms/step - loss: 613.4544 - mse: 613.4544
Epoch 5/50
95/95 [==============================] - 0s 883us/step - loss: 613.4542 - mse: 613.4542
Epoch 6/50
95/95 [==============================] - 0s 1ms/step - loss: 613.4544 - mse: 613.4544
Epoch 7/50
95/95 [==============================] - 0s 958us/step - loss: 613.4543 - mse: 613.4543
Epoch 8/50
95/95 [==============================] - 0s 965us/step - loss: 613.4542 - mse: 613.4542
Epoch 9/50
95/95 [==============================] - 0s 979us/step - loss: 613.4542 - mse: 613.4542
Epoch 10/50
95/95 [==============================] - 0s 1ms/step - loss: 613.4543 - mse: 613.4543
Epoch 11/50
95/95 [==

In [5]:
model.evaluate(x_test, y_test)

4/4 [==============================] - 0s 1ms/step - loss: 528.5603 - mse: 528.5603


[528.560302734375, 528.560302734375]

### 문제 2. 유방암 데이터셋(Breast Cancer)

In [6]:
from sklearn.datasets import load_breast_cancer

# 데이터 불러오기
cancer = load_breast_cancer()
cancer_df = pd.DataFrame(data=cancer.data, columns=cancer.feature_names)
cancer_df['target'] = cancer.target
cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [7]:
cancer_df.shape

(569, 31)

In [8]:
cancer_df['target'].unique()

array([0, 1])

In [9]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

y = cancer_df['target']
x = cancer_df.drop(['target'], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42)

model = Sequential()
model.add(Dense(40, input_dim = 30, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(loss = 'binary_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 40)                1240      
                                                                 
 dense_3 (Dense)             (None, 1)                 41        
                                                                 
Total params: 1,281
Trainable params: 1,281
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.fit(x_train, y_train, epochs = 50, batch_size = 8)

Epoch 1/50
54/54 [==============================] - 1s 1ms/step - loss: 10.0676 - accuracy: 0.6174
Epoch 2/50
54/54 [==============================] - 0s 1ms/step - loss: 0.5931 - accuracy: 0.8991
Epoch 3/50
54/54 [==============================] - 0s 1ms/step - loss: 0.4665 - accuracy: 0.9014
Epoch 4/50
54/54 [==============================] - 0s 1ms/step - loss: 0.4100 - accuracy: 0.8873
Epoch 5/50
54/54 [==============================] - 0s 1ms/step - loss: 0.4952 - accuracy: 0.8803
Epoch 6/50
54/54 [==============================] - 0s 2ms/step - loss: 0.3840 - accuracy: 0.8991
Epoch 7/50
54/54 [==============================] - 0s 2ms/step - loss: 0.5581 - accuracy: 0.8638
Epoch 8/50
54/54 [==============================] - 0s 1ms/step - loss: 0.4313 - accuracy: 0.9014
Epoch 9/50
54/54 [==============================] - 0s 1ms/step - loss: 0.5892 - accuracy: 0.8638
Epoch 10/50
54/54 [==============================] - 0s 1ms/step - loss: 0.6098 - accuracy: 0.8638
Epoch 11/50
54/54 

In [11]:
model.evaluate(x_test, y_test)

5/5 [==============================] - 0s 1ms/step - loss: 0.3111 - accuracy: 0.9301


[0.3110685646533966, 0.9300699234008789]

In [12]:
model.predict(x_test)[0]

5/5 [==============================] - 0s 1ms/step


array([0.9961825], dtype=float32)

### 문제3. 당뇨 데이터셋(Diabetes)

In [13]:
from sklearn.datasets import load_diabetes

# 데이터 불러오기
diabetes = load_diabetes()
diabetes_df = pd.DataFrame(data=diabetes.data, columns=diabetes.feature_names)
diabetes_df['target'] = diabetes.target
diabetes_df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

In [14]:
diabetes_df.shape

(442, 11)

In [15]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

y = diabetes_df['target']
x = diabetes_df.drop(['target'], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42)

model = Sequential()
model.add(Dense(20, input_dim = 10, activation = 'relu'))
model.add(Dense(1, activation = 'relu'))

model.compile(loss = 'mean_squared_error',
             optimizer = 'adam',
             metrics = ['mse'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 20)                220       
                                                                 
 dense_5 (Dense)             (None, 1)                 21        
                                                                 
Total params: 241
Trainable params: 241
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.fit(x_train, y_train, epochs = 50, batch_size = 8)

Epoch 1/50
42/42 [==============================] - 0s 1ms/step - loss: 29853.6582 - mse: 29853.6582
Epoch 2/50
42/42 [==============================] - 0s 1ms/step - loss: 29802.8770 - mse: 29802.8770
Epoch 3/50
42/42 [==============================] - 0s 1ms/step - loss: 29737.7246 - mse: 29737.7246
Epoch 4/50
42/42 [==============================] - 0s 1ms/step - loss: 29658.9609 - mse: 29658.9609
Epoch 5/50
42/42 [==============================] - 0s 1ms/step - loss: 29565.3633 - mse: 29565.3633
Epoch 6/50
42/42 [==============================] - 0s 1ms/step - loss: 29456.8066 - mse: 29456.8066
Epoch 7/50
42/42 [==============================] - 0s 1ms/step - loss: 29332.0488 - mse: 29332.0488
Epoch 8/50
42/42 [==============================] - 0s 1ms/step - loss: 29191.7441 - mse: 29191.7441
Epoch 9/50
42/42 [==============================] - 0s 1ms/step - loss: 29037.9062 - mse: 29037.9062
Epoch 10/50
42/42 [==============================] - 0s 1ms/step - loss: 28867.9180 - mse: 

In [17]:
model.evaluate(x_test, y_test)

4/4 [==============================] - 0s 2ms/step - loss: 11966.4736 - mse: 11966.4736


[11966.4736328125, 11966.4736328125]

### 문제4. 숫자 데이터셋(Digits)

In [18]:
from sklearn.datasets import load_digits

# 데이터 불러오기
digits = load_digits()
digits_df = pd.DataFrame(data=digits.data, columns=digits.feature_names)
digits_df['target'] = digits.target
digits_df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [19]:
digits_df.shape

(1797, 65)

In [20]:
digits_df['target'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

y = digits_df['target']
x = digits_df.drop(['target'], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42)

model = Sequential()
model.add(Dense(80, input_dim = 64, activation = 'relu'))
model.add(Dense(10, activation = 'softmax'))

model.compile(loss = 'sparse_categorical_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 80)                5200      
                                                                 
 dense_7 (Dense)             (None, 10)                810       
                                                                 
Total params: 6,010
Trainable params: 6,010
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.fit(x_train, y_train, epochs = 50, batch_size = 8)

Epoch 1/50
169/169 [==============================] - 1s 1ms/step - loss: 1.7360 - accuracy: 0.6095
Epoch 2/50
169/169 [==============================] - 0s 1ms/step - loss: 0.2654 - accuracy: 0.9198
Epoch 3/50
169/169 [==============================] - 0s 1ms/step - loss: 0.1489 - accuracy: 0.9525
Epoch 4/50
169/169 [==============================] - 0s 1ms/step - loss: 0.1002 - accuracy: 0.9718
Epoch 5/50
169/169 [==============================] - 0s 1ms/step - loss: 0.0696 - accuracy: 0.9814
Epoch 6/50
169/169 [==============================] - 0s 1ms/step - loss: 0.0465 - accuracy: 0.9933
Epoch 7/50
169/169 [==============================] - 0s 1ms/step - loss: 0.0397 - accuracy: 0.9903
Epoch 8/50
169/169 [==============================] - 0s 1ms/step - loss: 0.0286 - accuracy: 0.9963
Epoch 9/50
169/169 [==============================] - 0s 1ms/step - loss: 0.0245 - accuracy: 0.9963
Epoch 10/50
169/169 [==============================] - 0s 1ms/step - loss: 0.0210 - accuracy: 0.9963

In [23]:
model.evaluate(x_test, y_test)

15/15 [==============================] - 0s 1ms/step - loss: 0.0773 - accuracy: 0.9844


[0.07728289067745209, 0.9844444394111633]

### 문제5. 와인 데이터 셋(Wine)

In [24]:
from sklearn.datasets import load_wine

# 데이터 불러오기
wine = load_wine()
wine_df = pd.DataFrame(data=wine.data, columns=wine.feature_names)
wine_df['target'] = wine.target
wine_df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [25]:
wine_df.shape

(178, 14)

In [26]:
wine_df['target'].unique()

array([0, 1, 2])

In [27]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

y = wine_df['target']
x = wine_df.drop(['target'], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42)

model = Sequential()
model.add(Dense(20, input_dim = 13, activation = 'relu'))
model.add(Dense(3, activation = 'softmax'))

model.compile(loss = 'sparse_categorical_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 20)                280       
                                                                 
 dense_9 (Dense)             (None, 3)                 63        
                                                                 
Total params: 343
Trainable params: 343
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.fit(x_train, y_train, epochs = 40, batch_size = 4)

Epoch 1/40
34/34 [==============================] - 0s 2ms/step - loss: 60.6649 - accuracy: 0.2707
Epoch 2/40
34/34 [==============================] - 0s 1ms/step - loss: 29.1866 - accuracy: 0.2180
Epoch 3/40
34/34 [==============================] - 0s 1ms/step - loss: 12.3579 - accuracy: 0.1353
Epoch 4/40
34/34 [==============================] - 0s 1ms/step - loss: 3.0417 - accuracy: 0.5489
Epoch 5/40
34/34 [==============================] - 0s 1ms/step - loss: 1.9986 - accuracy: 0.5564
Epoch 6/40
34/34 [==============================] - 0s 1ms/step - loss: 1.6149 - accuracy: 0.6842
Epoch 7/40
34/34 [==============================] - 0s 1ms/step - loss: 1.3831 - accuracy: 0.6617
Epoch 8/40
34/34 [==============================] - 0s 1ms/step - loss: 1.4156 - accuracy: 0.6992
Epoch 9/40
34/34 [==============================] - 0s 1000us/step - loss: 1.4415 - accuracy: 0.6692
Epoch 10/40
34/34 [==============================] - 0s 970us/step - loss: 1.3139 - accuracy: 0.6692
Epoch 11/40

In [29]:
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 3ms/step - loss: 0.3199 - accuracy: 0.8667


[0.3199244737625122, 0.8666666746139526]

In [30]:
y_pred = model.predict(x_test)

2/2 [==============================] - 0s 3ms/step


In [31]:
y_pred[0]

array([2.4702441e-02, 9.7503883e-01, 2.5874778e-04], dtype=float32)