# 3.1.1 배열이란?

In [ ]:
import numpy as np

In [ ]:
from numpy import *

# 3.1.2 배열 만들기

## np.array()

In [ ]:
import numpy as np

list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

## np.zeros()

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## np.ones()

In [ ]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

## np.empty()

In [ ]:
np.empty(5)

array([4.94065646e-324, 4.94065646e-324, 0.00000000e+000, 0.00000000e+000,
       6.23036978e-307])

## np.arange()

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

## np.random.rand()

In [ ]:
np.random.rand(2,3)

array([[0.70124992, 0.18151263, 0.91928056],
       [0.46747185, 0.03213624, 0.89690772]])

## np.reshape()

In [ ]:
arr2 = np.arange(16)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr2.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

## shape, dtype(), astype()

In [ ]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr.shape

(16,)

In [ ]:
arr.dtype

dtype('int32')

In [ ]:
arr.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

# 3.1.3 선택

In [ ]:
import numpy as np
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# 기본 인덱스
arr[5]

5

In [ ]:
# 마이너스 인덱스
arr[-1]

15

In [ ]:
# 인덱스 범위
arr[5:8]

array([5, 6, 7])

## ① 기본 인덱스

In [ ]:
# 값 할당
arr[5] = 100
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [ ]:
# 여러 값 할당
arr[6:8] = [200, 201]
arr

array([  0,   1,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

In [ ]:
# 다차원 배열
arr2 = np.arange(16).reshape(4,4) # 메쏘드 체인
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr2[1]

array([4, 5, 6, 7])

In [ ]:
arr2[1][1]

5

In [ ]:
arr2[1,2] #arr2[1][2]와 동일

6

In [ ]:
arr2[1,2] = 100 # 값 할당
arr2

array([[  0,   1,   2,   3],
       [  4,   5, 100,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [ ]:
arr2[0:2]

array([[  0,   1,   2,   3],
       [  4,   5, 100,   7]])

In [ ]:
arr2[:2] #arr2[0:2]와 동일

array([[  0,   1,   2,   3],
       [  4,   5, 100,   7]])

In [ ]:
arr2[0:2, 2:4]

array([[  2,   3],
       [100,   7]])

In [ ]:
arr2[:2, 2:]

array([[  2,   3],
       [100,   7]])

## ② 불리언 인덱스

In [ ]:
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [ ]:
score_arr >= 90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [ ]:
score_arr[score_arr >= 90]

array([90, 95, 90])

In [ ]:
score_arr[score_arr >= 90] = 999
score_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])

# 3.1.4 연산

## 기본 사칙 연산

In [ ]:
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [ ]:
arr + 2

array([3, 4, 5, 6])

In [ ]:
arr * 2

array([2, 4, 6, 8])

In [ ]:
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [ ]:
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
arr1 = np.arange(5, 9)
arr1

array([5, 6, 7, 8])

In [ ]:
arr + arr1

array([ 6,  8, 10, 12])

In [ ]:
list1 = [5, 6, 7, 8]
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

## 주요 산술 연산 함수

In [ ]:
# 제곱
np.square(arr)

array([ 1,  4,  9, 16], dtype=int32)

In [ ]:
# 제곱근(루트)
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
# exp(지수승)
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
# log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
# 더하기
np.add(arr, arr1)

array([ 6,  8, 10, 12])

In [ ]:
#합계
np.sum(arr)

10

In [ ]:
#누적합
np.cumsum(arr)

array([ 1,  3,  6, 10], dtype=int32)

In [ ]:
# 평균
np.mean(arr)

2.5

In [ ]:
# 편차
np.var(arr)

1.25

In [ ]:
# 표준편차
np.std(arr)

1.118033988749895

In [ ]:
# 최소값
np.min(arr)

1

In [ ]:
# 최대값
np.max(arr)

4

In [ ]:
# 최소값의 인덱스
np.argmin(arr)

0

In [ ]:
# 최대값의 인덱스
np.argmax(arr)

3

# 3.1.5 변형

In [ ]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
arr.T #arr.transpose()와 동일

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
arr3d = np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr3d.transpose() #transpose(2,1,0)와 동일

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [ ]:
arr3d.transpose(1,0,2)

array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])

# 3.1.6 저장

In [ ]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.save('array', arr)

In [ ]:
load_arr = np.load('array.npy')

In [ ]:
load_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])